title: Jesse's Epic Stuff
author: Jesse Neal
email: Email jesseneal9@gmail.com
theme: minima
description: This site shows all the things that I have learned to do. This includes programming, woodwork, and other stuff I like to show off.

# social links
github_username:  broncbuster3

show_excerpts: true # set to false to remove excerpts on the homepage
